services:
  dsite:
    image: ghcr.io/demen1n/dsite:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /data:/data
    environment:
      - SECURE_COOKIES=true
      - SITE_TITLE=Дмитрий Деменин
      - SITE_DESC=Программист и фотограф
    mem_limit: 256m
    cpus: "0.5"
